#!/bin/bash
#===============================================================================
# HyperCalibrate - Manual Installation Script for Raspberry Pi
#
# This script installs HyperCalibrate on a Raspberry Pi manually.
# For automated deployment from a dev machine, use deploy.sh instead.
#
# Usage: sudo ./install-rpi.sh
#===============================================================================

set -e

#-------------------------------------------------------------------------------
# Configuration - Edit these values as needed
#-------------------------------------------------------------------------------
INPUT_DEVICE="${INPUT_DEVICE:-/dev/video0}"
OUTPUT_DEVICE="${OUTPUT_DEVICE:-/dev/video10}"
VIDEO_NR="${OUTPUT_DEVICE##*/video}"  # Extract number from device path
CAPTURE_WIDTH="${CAPTURE_WIDTH:-640}"
CAPTURE_HEIGHT="${CAPTURE_HEIGHT:-480}"
CAPTURE_FPS="${CAPTURE_FPS:-30}"
WEB_PORT="${WEB_PORT:-8091}"
WEB_HOST="${WEB_HOST:-0.0.0.0}"

echo "🍓 Installing HyperCalibrate on Raspberry Pi..."
echo "   Input:  $INPUT_DEVICE"
echo "   Output: $OUTPUT_DEVICE"
echo "   Web UI: http://$(hostname -I | awk '{print $1}'):$WEB_PORT"
echo ""

# Check if running on Raspberry Pi
if ! grep -q "Raspberry Pi" /proc/cpuinfo 2>/dev/null && ! grep -q "BCM" /proc/cpuinfo 2>/dev/null; then
    echo "⚠️  Warning: This doesn't appear to be a Raspberry Pi"
    read -p "Continue anyway? [y/N] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Install dependencies
echo "📦 Installing system dependencies..."
sudo apt update
sudo apt install -y v4l-utils v4l2loopback-dkms

# Load v4l2loopback module
# NOTE: exclusive_caps=0 is required to prevent Hyperion from crashing
# when it enumerates video devices at startup
echo "🔧 Setting up virtual camera device..."
sudo modprobe -r v4l2loopback 2>/dev/null || true
sudo modprobe v4l2loopback devices=1 video_nr=$VIDEO_NR card_label="HyperCalibrate" exclusive_caps=0

# Pre-configure the virtual camera format and enable keep_format
# This allows our app to set the format and write frames successfully
echo "📹 Configuring virtual camera format..."
sudo v4l2-ctl -d /dev/video$VIDEO_NR --set-fmt-video-out="width=$CAPTURE_WIDTH,height=$CAPTURE_HEIGHT,pixelformat=YUYV" 2>/dev/null || true
sudo v4l2-ctl -d /dev/video$VIDEO_NR --set-ctrl keep_format=1 2>/dev/null || true

# Make v4l2loopback persistent
echo "v4l2loopback" | sudo tee /etc/modules-load.d/v4l2loopback.conf > /dev/null
echo "options v4l2loopback devices=1 video_nr=$VIDEO_NR card_label=HyperCalibrate exclusive_caps=0" | sudo tee /etc/modprobe.d/v4l2loopback.conf > /dev/null

# Install binary
echo "📋 Installing binary..."
BINARY_PATH="./hypercalibrate"
if [ ! -f "$BINARY_PATH" ]; then
    BINARY_PATH="./dist/hypercalibrate"
fi
if [ ! -f "$BINARY_PATH" ]; then
    BINARY_PATH="./target/release/hypercalibrate"
fi
if [ ! -f "$BINARY_PATH" ]; then
    BINARY_PATH="./target/aarch64-unknown-linux-gnu/release/hypercalibrate"
fi

if [ -f "$BINARY_PATH" ]; then
    sudo install -m 755 "$BINARY_PATH" /usr/local/bin/hypercalibrate
else
    echo "⚠️  Binary not found. Build first with: ./docker-build.sh (or ./scripts/local-build.sh rpi)"
    exit 1
fi

# Install setup script for v4l2loopback
SETUP_SCRIPT="./scripts/setup-v4l2loopback.sh"
if [ ! -f "$SETUP_SCRIPT" ]; then
    SETUP_SCRIPT="./setup-v4l2loopback.sh"
fi
if [ -f "$SETUP_SCRIPT" ]; then
    sudo install -m 755 "$SETUP_SCRIPT" /usr/local/bin/hypercalibrate-setup-v4l2loopback
else
    echo "⚠️  Warning: setup-v4l2loopback.sh not found, using inline commands"
fi

# Install coordinated restart script (handles Hyperion restart order)
RESTART_SCRIPT="./scripts/restart-with-hyperion.sh"
if [ ! -f "$RESTART_SCRIPT" ]; then
    RESTART_SCRIPT="./restart-with-hyperion.sh"
fi
if [ -f "$RESTART_SCRIPT" ]; then
    sudo install -m 755 "$RESTART_SCRIPT" /usr/local/bin/hypercalibrate-restart
    echo "   Installed coordinated restart script"
else
    echo "⚠️  Warning: restart-with-hyperion.sh not found"
fi

# Create config directory and config file
echo "📁 Setting up configuration..."
sudo mkdir -p /etc/hypercalibrate

# Generate config file with proper values
sudo tee /etc/hypercalibrate/config.toml > /dev/null << TOML_CONFIG
# HyperCalibrate Configuration
# Generated by install-rpi.sh

[video]
input_device = "$INPUT_DEVICE"
output_device = "$OUTPUT_DEVICE"
width = $CAPTURE_WIDTH
height = $CAPTURE_HEIGHT
fps = $CAPTURE_FPS

[server]
host = "$WEB_HOST"
port = $WEB_PORT

[calibration]
enabled = true

[[calibration.corners]]
x = 0.1
y = 0.1

[[calibration.corners]]
x = 0.9
y = 0.1

[[calibration.corners]]
x = 0.9
y = 0.9

[[calibration.corners]]
x = 0.1
y = 0.9

# Edge points are dynamic - start with none, add via UI with Shift+Click
# Remove points with Ctrl+Click
edge_points = []
TOML_CONFIG

# Create systemd service
# NOTE: hypercalibrate starts BEFORE Hyperion so /dev/video10 exists when Hyperion starts
# The setup script reads resolution from config.toml, so changes via web UI are applied on restart
echo "⚙️  Creating systemd service..."
sudo tee /etc/systemd/system/hypercalibrate.service > /dev/null << SERVICE_FILE
[Unit]
Description=HyperCalibrate - TV Screen Calibration for Hyperion
After=network.target
Before=hyperion@hyperion.service hyperiond.service hyperion.service

[Service]
Type=simple
User=root
# Setup script reads resolution from config.toml and configures v4l2loopback
ExecStartPre=/usr/local/bin/hypercalibrate-setup-v4l2loopback /etc/hypercalibrate/config.toml
ExecStart=/usr/local/bin/hypercalibrate --config /etc/hypercalibrate/config.toml
# Use coordinated restart script instead of simple restart
ExecReload=/usr/local/bin/hypercalibrate-restart
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
SERVICE_FILE

# Reload systemd and enable service
echo "🚀 Enabling service..."
sudo systemctl daemon-reload
sudo systemctl enable hypercalibrate

echo ""
echo "✅ Installation complete!"
echo ""
echo "📋 Next steps:"
echo "   1. Review configuration: sudo nano /etc/hypercalibrate/config.toml"
echo "   2. Start the service: sudo systemctl start hypercalibrate"
echo "   3. Open web UI: http://$(hostname -I | awk '{print $1}'):$WEB_PORT"
echo ""
echo "🎯 Configure in Hyperion:"
echo "   1. Go to Configuration → LED Hardware → LED Controller"
echo "   2. Add/edit your LED instance"
echo "   3. Under 'Grabber', select 'Platform Capture'"
echo "   4. Choose 'HyperCalibrate' ($OUTPUT_DEVICE) as input"
echo ""
echo "🔧 Useful commands:"
echo "   - Check status: sudo systemctl status hypercalibrate"
echo "   - View logs: sudo journalctl -u hypercalibrate -f"
echo "   - Restart: sudo systemctl restart hypercalibrate"
echo "   - List cameras: v4l2-ctl --list-devices"
